name: ZeaHire Automation

on:
  schedule:
    - cron: "30 3 * * *"   # 9 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirement.txt
          pip install pytest playwright allure-pytest
          playwright install --with-deps

      - name: Run Tests
        run: |
          pytest -m smoke --alluredir=reports/allure-results --junitxml=reports/junit.xml

      # 🔥 INSTALL ALLURE
      - name: Install Allure
        run: npm install -g allure-commandline --save-dev

      # 🔥 GENERATE REPORT
      - name: Generate Allure Report
        run: |
          allure generate reports/allure-results --clean -o allure-report

      # 🔥 DEPLOY REPORT
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report