name: Zeahire Automation Tests

on:
  schedule:
    - cron: '30 3 * * *'   # 9 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install pytest pytest-playwright openpyxl
          playwright install --with-deps

      - name: Run Automation Script (with email)
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}
        run: |
          python run.py
