name: ZeaHire Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run Tests
        run: pytest --alluredir=allure-results || true

      - name: Send Email via Gmail SMTP
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.EMAIL_RECEIVERS }}
        run: python send_email.py